site_diag/symfony_diag/src/Entity/Actuality.php
<?php

namespace App\Entity;

use DateTimeInterface;
use App\Entity\Actuality;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ActualityRepository;
use Symfony\Component\HttpFoundation\File\File;


#[ORM\Entity(repositoryClass: ActualityRepository::class)]
class Actuality
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;


    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column(nullable: true)]
    private ?int $Importance = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $DateAj = null;

    #[ORM\Column(type: 'string')]
    private $brochureFilename;

    public function getBrochureFilename()
    {
        return $this->brochureFilename;
    }

    public function setBrochureFilename($brochureFilename)
    {
        $this->brochureFilename = $brochureFilename;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImportance(): ?int
    {
        return $this->Importance;
    }

    public function setImportance(?int $Importance): self
    {
        $this->Importance = $Importance;

        return $this;
    }

    public function getDateAj(): ?\DateTimeInterface
    {
        return $this->DateAj;
    }

    public function setDateAj(\DateTimeInterface $DateAj): self
    {
        $this->DateAj = $DateAj;

        return $this;
    }
}

site_diag/symfony_diag/templates/actuality.html.twig
{% extends 'base.html.twig' %}

{% block body %}
  <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container py-5">
      <div class="section-title text-center position-relative pb-3 mb-5 mx-auto" style="max-width: 600px;">
        <h5 class="fw-bold text-primary text-uppercase">Actualité</h5>
        <h1 class="mb-0">Vous pouvez voir ci dessous les dernieres actualités publiés</h1>
      </div>
      <div class="row g-5">
        {% for i, actuality in actualities %}
        <div class="col-lg-4 wow slideInUp" data-wow-delay="{{ loop.index * 0.3 }}s">
          <div class="card h-100">
            <img class="card-img-top img-fluid w-100" style="height: 200px;" src="./uploads/{{ actuality.brochureFilename }}" alt="{{ actuality.nom }}">
            <div class="card-body">
              <h4 class="card-title">{{ actuality.nom }}</h4>
              <p class="card-text">{{ actuality.description }}</p>
              <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#description-modal-{{ actuality.id }}">Lire plus</button>
            </div>
          </div>
          <div class="modal fade" id="description-modal-{{ actuality.id }}" tabindex="-1" aria-labelledby="description-modal-{{ actuality.id }}-label" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="description-modal-{{ actuality.id }}-label">{{ actuality.nom }}</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  {{ actuality.description }}
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

site_diag/symfony_diag/templates/actudesc.html.twig
{% block body %}
<link href="./css/login-style.css" rel="stylesheet">
    {% if error %}
        <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}
	<form action="{{ path('app_login') }}"
                        method="post">
    <div class="login-wrap">
	<div class="login-html">
		<input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Se connecter</label>
		<input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">S'inscrire</label>
		<div class="login-form">
			<div class="sign-in-htm">
				<div class="group">
					<label class="label" for="username">
                                <span class="label-text">
                                    Nom d'utilisateur
                                </span>
                            </label>
                            <input
                                class="input input-bordered"
                                type="text"
                                id="username"
                                name="_username"
                                value="{{ last_username }}"
                            />
				</div>
				<div class="group">
					<label class="label" for="password">
                                <span class="label-text"> Mot de passe </span>
                            </label>
                            <input
                                class="input input-bordered"
                                type="password"
                                name="_password"
                                id="password"
                            />
				</div>
				<div class="group">
					<input id="check" type="checkbox" class="check" checked>
					<label for="check"><span class="icon"></span> Me garder connecter</label>
				</div>
				<div class="group">
					<input
                            class="input"
                            type="hidden"
                            name="_csrf_token"
                            value="{{ csrf_token('authenticate') }}"
                        />
						<button class="btn" type="submit">
                                Se connecter
                            </button>
				</div>
				<div class="hr"></div>
				<div class="foot-lnk">
					<a href="#forgot">Mot de passe oublié ?</a>
				</div>
			</div>
			{% for flash_error in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
    {% endfor %}
	<h1>Register</h1>

{% set registrationForm = form('App\\Form\\RegistrationFormType') %}

{{ form_start(registrationForm) }}
    <div class="group">
        {{ form_widget(registrationForm.email, { 'attr': {'class': 'input', 'id': 'user'} }) }}
        {{ form_label(registrationForm.email, 'Email', { 'label_attr': {'class': 'label'} }) }}
    </div>
    <div class="group">
        {{ form_widget(registrationForm.plainPassword, { 'attr': {'class': 'input', 'id': 'pass', 'data-type': 'password'} }) }}
        {{ form_label(registrationForm.plainPassword, 'Mot de passe', { 'label_attr': {'class': 'label'} }) }}
    </div>
    <div class="group">
        {{ form_widget(registrationForm.passwordRepeat, { 'attr': {'class': 'input', 'id': 'pass2', 'data-type': 'password'} }) }}
    {{ form_label(registrationForm.passwordRepeat, 'Ressaisir mot de passe', { 'label_attr': {'class': 'label'} }) }}
</div>
<div class="group">
    {{ form_widget(registrationForm.address, { 'attr': {'class': 'input', 'id': 'address'} }) }}
    {{ form_label(registrationForm.address, 'Adresse', { 'label_attr': {'class': 'label'} }) }}
</div>
<div class="group">
    {{ form_widget(registrationForm.agreeTerms, { 'attr': {'class': 'input', 'id': 'agreeTerms'} }) }}
    {{ form_label(registrationForm.agreeTerms, 'Agree to terms', { 'label_attr': {'class': 'label'} }) }}
</div>
<div class="group">
    <button type="submit" class="button">S'inscrire</button>
</div>
{{ form_end(registrationForm) }}
<div class="hr"></div>
<div class="foot-lnk">
    <a href="#tab-1">Déjà membre ?</a>
</div>
</div>

{% endblock %}

site_diag/symfony_diag/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
            <link href="./img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&family=Rubik:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="./lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="./lib/animate/animate.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="./css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="./css/style.css" rel="stylesheet">
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
            <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="./lib/wow/wow.min.js"></script>
    <script src="./lib/easing/easing.min.js"></script>
    <script src="./lib/waypoints/waypoints.min.js"></script>
    <script src="./lib/counterup/counterup.min.js"></script>
    <script src="./lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="./js/main.js"></script>
        {% endblock %}
    </head>
    <body>
        {{include ("navbar.html.twig")}}
        {% block body %}{% endblock %}
    </body>
</html>

site_diag/symfony_diag/templates/navbar.html.twig
 <div class="container-fluid position-relative p-0">
        <nav class="navbar navbar-expand-lg navbar-dark px-5 py-3 py-lg-0">
            <a href="/" class="navbar-brand p-0">
                 <h1 class="m-0"><i class="fa fa-user-tie me-2"></i>Richardiag</h1> 
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="fa fa-bars"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto py-0">
                    <a href="/" class="nav-item nav-link active">Accueil</a>
                    <a href="/actualities" class="nav-item nav-link">Actualités</a>
                    <a href="service.html" class="nav-item nav-link">Nos services</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Demande de devis</a>
                        <div class="dropdown-menu m-0">
                            <a href="blog.html" class="dropdown-item">Maison</a>
                            <a href="detail.html" class="dropdown-item">Appartement</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Nous contacter</a>
                        <div class="dropdown-menu m-0">
                            <a href="http://r-diag.fr/" class="dropdown-item">Site Primaire</a>
                            <a href="https://www.pagesjaunes.fr/pros/61961254" class="dropdown-item">Page Jaune</a>
                        </div>
                    </div>
                </div>
                <div>
                        <ul>
                            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                            <li>
                                <a href="/logout" class="btn btn-primary py-2 px-4 ms-3">Se déconnecter</a>
                            </li>
                            {% else %}
                            <li>
                                <a href="/login" class="btn btn-primary py-2 px-4 ms-3">Se connecter</a>
                            </li>

                            {% endif %}
                        </ul>
                </div>
            </div>
        </nav>
    </div>